name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '8.0.x'
            
      - name: Restore dependencies
        run: dotnet restore Microservice-Fiap-Processa-Video.sln
        working-directory: .

      - name: Build Docker Image
        run: |
          docker build -t rafaelyuji/microservice-fiap-processa-video:latest -f FiapProcessaVideo.WebApi/Dockerfile .
          docker tag rafaelyuji/microservice-fiap-processa-video:latest rafaelyuji/microservice-fiap-processa-video:${{ github.sha }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push rafaelyuji/microservice-fiap-processa-video:latest
          docker push rafaelyuji/microservice-fiap-processa-video:${{ github.sha }}
